'use client';

import Link from 'next/link';
import { ArrowRight, Minus, Plus, ShoppingBag, Trash2 } from 'lucide-react';
import { AppHeader } from '@/components/AppHeader';
import { useCartStore } from '@/lib/cart-store';

export default function CartPage() {
  const { lines, remove, setQuantity } = useCartStore();
  const subtotal = lines.reduce((total, line) => total + line.price * line.quantity, 0);
  return <main className="min-h-screen bg-slate-50 text-ink"><AppHeader mode="buyer" /><div className="mx-auto max-w-7xl px-5 py-10 sm:px-8"><p className="text-xs font-bold uppercase tracking-[.16em] text-amber-700">Your bag</p><h1 className="mt-3 text-4xl font-black tracking-[-.05em]">Shopping cart</h1>{lines.length === 0 ? <div className="mt-10 rounded-3xl border border-dashed border-slate-300 bg-white p-16 text-center"><ShoppingBag className="mx-auto text-slate-300" size={48} /><h2 className="mt-5 text-xl font-bold">Your cart is empty</h2><p className="mt-2 text-slate-500">Discover wholesale and retail-ready products from Indian makers.</p><Link href="/products" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-ink px-5 py-3 font-bold text-white">Shop marketplace <ArrowRight size={16} /></Link></div> : <div className="mt-9 grid gap-6 lg:grid-cols-[1fr_360px]"><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white">{lines.map(line => <div key={line.variantId} className="flex gap-4 border-b border-slate-100 p-5 last:border-0"><img src={line.image} alt="" className="size-24 rounded-xl object-cover" /><div className="min-w-0 flex-1"><h2 className="font-bold">{line.title}</h2><p className="mt-1 text-xs text-slate-400">{line.variantName}</p><strong className="mt-3 block">₹{line.price.toLocaleString('en-IN')}</strong></div><div className="flex flex-col items-end justify-between"><button onClick={() => remove(line.variantId)} aria-label={`Remove ${line.title}`} className="text-slate-400 hover:text-rose-600"><Trash2 size={17} /></button><div className="flex items-center gap-2 rounded-lg border border-slate-200 p-1"><button onClick={() => setQuantity(line.variantId, line.quantity - 1)} className="grid size-7 place-items-center rounded hover:bg-slate-100"><Minus size={13} /></button><span className="w-5 text-center text-sm font-bold">{line.quantity}</span><button onClick={() => setQuantity(line.variantId, line.quantity + 1)} className="grid size-7 place-items-center rounded hover:bg-slate-100"><Plus size={13} /></button></div></div></div>)}</section><aside className="h-fit rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-bold">Order summary</h2><div className="mt-6 flex justify-between text-sm text-slate-500"><span>Subtotal</span><span>₹{subtotal.toLocaleString('en-IN')}</span></div><div className="mt-3 flex justify-between text-sm text-slate-500"><span>Shipping</span><span className="text-emerald-700">Calculated at checkout</span></div><div className="my-6 border-t border-slate-100 pt-5"><div className="flex justify-between"><strong>Total</strong><strong className="text-xl">₹{subtotal.toLocaleString('en-IN')}</strong></div></div><Link href="/checkout" className="flex items-center justify-center gap-2 rounded-xl bg-ink py-3.5 font-bold text-white">Proceed to checkout <ArrowRight size={16} /></Link></aside></div>}</div></main>;
}
