import { MessageCircle, Users, Zap } from 'lucide-react';
import { AppHeader } from '@/components/AppHeader';

const leads = [
  { buyer: 'Aarav Retail, Delhi', item: 'Banarasi silk stoles', qty: '500 units', status: 'NEW' },
  { buyer: 'Mehta Home, Mumbai', item: 'Bhadohi cotton rugs', qty: '120 pieces', status: 'QUOTED' },
];

export default function AdminLeadsPage() {
  return <main className="min-h-screen bg-slate-50 text-ink"><AppHeader mode="ops" /><div className="mx-auto max-w-7xl px-5 py-10 sm:px-8"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-amber-700">Ops console / inbound</p><h1 className="mt-3 text-4xl font-black tracking-[-.05em] sm:text-5xl">Lead automation center</h1><p className="mt-3 text-slate-500">Every enquiry, routed to a faster quote.</p></div><button className="inline-flex items-center gap-2 rounded-lg bg-ink px-4 py-3 text-sm font-bold text-white"><Zap size={16} />Run lead sync</button></div><div className="mt-9 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl bg-ink p-5 text-white"><Users className="text-amber-400" size={20} /><p className="mt-8 text-sm text-indigo-200">New leads today</p><strong className="text-4xl">24</strong></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><MessageCircle className="text-amber-600" size={20} /><p className="mt-8 text-sm text-slate-500">Quotes sent</p><strong className="text-4xl">18</strong></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><Zap className="text-emerald-600" size={20} /><p className="mt-8 text-sm text-slate-500">Avg. response time</p><strong className="text-4xl">11m</strong></div></div><div className="mt-8 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><h2 className="font-bold">Recent inbound leads</h2><button className="text-sm font-bold text-amber-700">View all</button></div><div className="hidden grid-cols-[1.2fr_1.2fr_.6fr_.6fr_auto] gap-4 border-b border-slate-100 px-5 py-3 text-[11px] font-bold uppercase tracking-wider text-slate-400 md:grid"><span>Buyer</span><span>Request</span><span>Quantity</span><span>Status</span><span /></div>{leads.map(lead => <div key={lead.buyer} className="grid gap-3 border-b border-slate-100 px-5 py-5 last:border-0 md:grid-cols-[1.2fr_1.2fr_.6fr_.6fr_auto] md:items-center md:gap-4"><div><span className="font-bold">{lead.buyer}</span><p className="mt-1 text-xs text-slate-400">IndiaMART &middot; 8 min ago</p></div><span className="text-sm text-slate-600">{lead.item}</span><span className="text-sm text-slate-600">{lead.qty}</span><span className={`w-fit rounded-full px-2.5 py-1 text-[10px] font-bold ${lead.status === 'NEW' ? 'bg-amber-100 text-amber-800' : 'bg-emerald-100 text-emerald-700'}`}>{lead.status}</span><button className="inline-flex w-fit items-center gap-1.5 rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white"><MessageCircle size={14} />Send quote</button></div>)}</div></div></main>;
}
